import type { Metadata } from "next";
import localFont from "next/font/local";
import { Irish_Grover, Inria_Sans } from 'next/font/google';
import Link from 'next/link';
import "./globals.css";

import { Button } from "@mui/material";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const irishGrover = Irish_Grover({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-irish-grover',
});

const inriaSans = Inria_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-inria-sans',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  headerContent,
}: Readonly<{
  children: React.ReactNode;
  headerContent?: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${irishGrover.variable} ${inriaSans.variable}`}>
        <header className="flex justify-between p-5">
          <h1 className="font-grover text-3xl text-orange6">Pizaroo</h1>
          <div className='flex'>
            <div className="flex items-center justify-center space-x-4">
              <Button variant="outlined" size='small' className='border border-gray2 text-gray4'><Link href="/login">Login</Link></Button>
              <Button variant="outlined" size='small' className='border border-gray2 text-gray4'><Link href="/signup">Sign up</Link></Button>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
